let
    Source = Folder.Files("INSERT_FILE_PATHWAY"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (4)", each #"Transform File (4)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (4)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (4)", Table.ColumnNames(#"Transform File (4)"(#"Sample File (4)"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"response_uuid", type text}, {"child_hashed_id", type text}, {"frame_id", type text}, {"event_number", Int64.Type}, {"key", type text}, {"value", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"event_number", "Source.Name"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Columns", "frame_id", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"frame_id.1", "frame_id.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"frame_id.1", type text}, {"frame_id.2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"frame_id.1"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Columns1", each ([frame_id.2] = "Ask1-ADJ0A-Question" or [frame_id.2] = "Ask1-ADJ0A-Question-repeat-1" or [frame_id.2] = "Ask1-ADJ0B-Question" or [frame_id.2] = "Ask1-ADJ0B-Question-repeat-1" or [frame_id.2] = "Ask1-ADJ1A-Question" or [frame_id.2] = "Ask1-ADJ1B-Question" or [frame_id.2] = "Ask1-ADJ2A-Question" or [frame_id.2] = "Ask1-ADJ2A-Question-repeat-1" or [frame_id.2] = "Ask1-ADJ2B-Question" or [frame_id.2] = "Ask1-ARG0A-Question" or [frame_id.2] = "Ask1-ARG0A-Question-repeat-1" or [frame_id.2] = "Ask1-ARG0A-Question-repeat-2" or [frame_id.2] = "Ask1-ARG0B-Question" or [frame_id.2] = "Ask1-ARG0B-Question-repeat-1" or [frame_id.2] = "Ask1-ARG1A-Question" or [frame_id.2] = "Ask1-ARG1A-Question-repeat-1" or [frame_id.2] = "Ask1-ARG1A-Question-repeat-2" or [frame_id.2] = "Ask1-ARG1B-Question" or [frame_id.2] = "Ask1-ARG1B-Question-repeat-1" or [frame_id.2] = "Ask1-ARG2A-Question" or [frame_id.2] = "Ask1-ARG2A-Question-repeat-1" or [frame_id.2] = "Ask1-ARG2A-Question-repeat-2" or [frame_id.2] = "Ask1-ARG2B-Question" or [frame_id.2] = "Ask1-ARG2B-Question-repeat-1" or [frame_id.2] = "Ask2-ADJ0A-Question" or [frame_id.2] = "Ask2-ADJ0A-Question-repeat-1" or [frame_id.2] = "Ask2-ADJ0B-Question" or [frame_id.2] = "Ask2-ADJ0B-Question-repeat-1" or [frame_id.2] = "Ask2-ADJ1A-Question" or [frame_id.2] = "Ask2-ADJ1A-Question-repeat-1" or [frame_id.2] = "Ask2-ADJ1B-Question" or [frame_id.2] = "Ask2-ADJ1B-Question-repeat-1" or [frame_id.2] = "Ask2-ADJ1B-Question-repeat-2" or [frame_id.2] = "Ask2-ADJ2A-Question" or [frame_id.2] = "Ask2-ADJ2B-Question" or [frame_id.2] = "Ask2-ADJ2B-Question-repeat-1" or [frame_id.2] = "Ask2-ADJ2B-Question-repeat-2" or [frame_id.2] = "Ask2-ARG0A-Question" or [frame_id.2] = "Ask2-ARG0A-Question-repeat-1" or [frame_id.2] = "Ask2-ARG0A-Question-repeat-2" or [frame_id.2] = "Ask2-ARG0B-Question" or [frame_id.2] = "Ask2-ARG0B-Question-repeat-1" or [frame_id.2] = "Ask2-ARG1A-Question" or [frame_id.2] = "Ask2-ARG1A-Question-repeat-1" or [frame_id.2] = "Ask2-ARG1B-Question" or [frame_id.2] = "Ask2-ARG2A-Question" or [frame_id.2] = "Ask2-ARG2A-Question-repeat-1" or [frame_id.2] = "Ask2-ARG2B-Question" or [frame_id.2] = "Ask2-ARG2B-Question-repeat-1" or [frame_id.2] = "Ask2-ARG2B-Question-repeat-2" or [frame_id.2] = "Ask2-ARG2B-Question-repeat-3" or [frame_id.2] = "Promise1-ADJ0A-Question" or [frame_id.2] = "Promise1-ADJ0A-Question-repeat-1" or [frame_id.2] = "Promise1-ADJ0B-Question" or [frame_id.2] = "Promise1-ADJ1A-Question" or [frame_id.2] = "Promise1-ADJ1A-Question-repeat-1" or [frame_id.2] = "Promise1-ADJ1B-Question" or [frame_id.2] = "Promise1-ADJ2A-Question" or [frame_id.2] = "Promise1-ADJ2B-Question" or [frame_id.2] = "Promise1-ARG0A-Question" or [frame_id.2] = "Promise1-ARG0B-Question" or [frame_id.2] = "Promise1-ARG0B-Question-repeat-1" or [frame_id.2] = "Promise1-ARG0B-Question-repeat-2" or [frame_id.2] = "Promise1-ARG1A-Question" or [frame_id.2] = "Promise1-ARG1A-Question-repeat-1" or [frame_id.2] = "Promise1-ARG1B-Question" or [frame_id.2] = "Promise1-ARG1B-Question-repeat-1" or [frame_id.2] = "Promise1-ARG2A-Question" or [frame_id.2] = "Promise1-ARG2A-Question-repeat-1" or [frame_id.2] = "Promise1-ARG2B-Question" or [frame_id.2] = "Promise1-ARG2B-Question-repeat-1" or [frame_id.2] = "Promise2-ADJ0A-Question" or [frame_id.2] = "Promise2-ADJ0A-Question-repeat-1" or [frame_id.2] = "Promise2-ADJ0B-Question" or [frame_id.2] = "Promise2-ADJ1A-Question" or [frame_id.2] = "Promise2-ADJ1B-Question" or [frame_id.2] = "Promise2-ADJ1B-Question-repeat-1" or [frame_id.2] = "Promise2-ADJ2A-Question" or [frame_id.2] = "Promise2-ADJ2A-Question-repeat-1" or [frame_id.2] = "Promise2-ADJ2B-Question" or [frame_id.2] = "Promise2-ADJ2B-Question-repeat-1" or [frame_id.2] = "Promise2-ARG0A-Question" or [frame_id.2] = "Promise2-ARG0A-Question-repeat-1" or [frame_id.2] = "Promise2-ARG0B-Question" or [frame_id.2] = "Promise2-ARG0B-Question-repeat-1" or [frame_id.2] = "Promise2-ARG1A-Question" or [frame_id.2] = "Promise2-ARG1A-Question-repeat-1" or [frame_id.2] = "Promise2-ARG1A-Question-repeat-2" or [frame_id.2] = "Promise2-ARG1A-Question-repeat-3" or [frame_id.2] = "Promise2-ARG1B-Question" or [frame_id.2] = "Promise2-ARG1B-Question-repeat-1" or [frame_id.2] = "Promise2-ARG1B-Question-repeat-2" or [frame_id.2] = "Promise2-ARG2A-Question" or [frame_id.2] = "Promise2-ARG2A-Question-repeat-1" or [frame_id.2] = "Promise2-ARG2B-Question") and ([key] = "images.1.id" or [key] = "images.1.src" or [key] = "images.2.id" or [key] = "images.2.src" or [key] = "images.3.id" or [key] = "images.3.src" or [key] = "images.4.id" or [key] = "images.4.src")),
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","INSERT_IMG_REPOSITORY_URL/button_","",Replacer.ReplaceText,{"value"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",".id","",Replacer.ReplaceText,{"key"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",".src","",Replacer.ReplaceText,{"key"}),
    #"Grouped Rows" = Table.Group(#"Replaced Value2", {"response_uuid", "child_hashed_id", "frame_id.2", "key"}, {{"Count", each Text.Combine([value], "; "), type nullable text}}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Grouped Rows", "Count", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Count.1", "Count.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Count.1", type text}, {"Count.2", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type2",{{"Count.1", "choice"}, {"Count.2", "image"}}),
    #"Replaced Value3" = Table.ReplaceValue(#"Renamed Columns",".jpg","",Replacer.ReplaceText,{"image"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3"," INSERT_IMG_REPOSITORY_URL/button_","",Replacer.ReplaceText,{"image"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Replaced Value4",{"response_uuid"})
in
    #"Removed Columns2"