let
    Source = Folder.Files("INSERT_FILE_PATHWAY"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"response_uuid", type text}, {"child_hashed_id", type text}, {"frame_id", type text}, {"event_number", Int64.Type}, {"key", type text}, {"value", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name", "event_number"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([key] = "images.0.src" or [key] = "images.1.id" or [key] = "images.1.src" or [key] = "images.2.id" or [key] = "images.2.src" or [key] = "images.3.id" or [key] = "images.3.src" or [key] = "images.4.id" or [key] = "images.4.src" or [key] = "images.5.id" or [key] = "images.5.src" or [key] = "selectedImage") and ([frame_id] <> "11-Ask2-ADJ0A-Exposition" and [frame_id] <> "11-Promise1-ARG0A-Exposition" and [frame_id] <> "11-Promise2-ADJ0B-Exposition" and [frame_id] <> "13-Ask2-ADJ2B-Exposition" and [frame_id] <> "13-Promise1-ARG2A-Exposition" and [frame_id] <> "13-Promise2-ARG1A-Exposition" and [frame_id] <> "15-Ask2-ADJ1A-Exposition" and [frame_id] <> "15-Promise1-ADJ2B-Exposition" and [frame_id] <> "15-Promise2-ARG2A-Exposition" and [frame_id] <> "17-Ask2-ARG1A-Exposition" and [frame_id] <> "17-Promise1-ADJ1A-Exposition" and [frame_id] <> "17-Promise2-ADJ2A-Exposition" and [frame_id] <> "19-rest" and [frame_id] <> "21-Promise1-ADJ1B-Exposition" and [frame_id] <> "21-Promise2-ARG1A-Exposition" and [frame_id] <> "21-Promise2-ARG1B-Exposition" and [frame_id] <> "23-Promise1-ARG2B-Exposition" and [frame_id] <> "23-Promise2-ADJ0A-Exposition" and [frame_id] <> "23-Promise2-ARG2B-Exposition" and [frame_id] <> "25-Promise1-ARG0A-Exposition" and [frame_id] <> "25-Promise2-ADJ1B-Exposition" and [frame_id] <> "25-Promise2-ARG0A-Exposition" and [frame_id] <> "27-Promise1-ADJ0A-Exposition" and [frame_id] <> "27-Promise2-ADJ2A-Exposition" and [frame_id] <> "27-Promise2-ARG2A-Exposition" and [frame_id] <> "29-Promise1-ADJ2B-Exposition" and [frame_id] <> "29-Promise2-ADJ2B-Exposition" and [frame_id] <> "29-Promise2-ARG0B-Exposition" and [frame_id] <> "31-Promise1-ARG1B-Exposition" and [frame_id] <> "31-Promise2-ADJ0B-Exposition" and [frame_id] <> "31-Promise2-ADJ1A-Exposition" and [frame_id] <> "33-rest" and [frame_id] <> "35-Ask1-ADJ2A-Exposition" and [frame_id] <> "35-Ask1-ARG1A-Exposition" and [frame_id] <> "35-Ask2-ARG2A-Exposition" and [frame_id] <> "37-Ask1-ADJ0B-Exposition" and [frame_id] <> "37-Ask1-ADJ2B-Exposition" and [frame_id] <> "37-Ask2-ARG0A-Exposition" and [frame_id] <> "37-Ask2-ARG0A-Exposition-repeat-1" and [frame_id] <> "39-Ask1-ARG1B-Exposition" and [frame_id] <> "39-Ask1-ARG1B-Exposition-repeat-1" and [frame_id] <> "39-Ask1-ARG2A-Exposition" and [frame_id] <> "39-Ask2-ARG1B-Exposition" and [frame_id] <> "4-character-intro1" and [frame_id] <> "41-Ask1-ADJ1A-Exposition" and [frame_id] <> "41-Ask1-ADJ1B-Exposition" and [frame_id] <> "41-Ask2-ADJ2A-Exposition" and [frame_id] <> "43-Ask1-ARG0B-Exposition" and [frame_id] <> "43-Ask1-ARG2A-Exposition" and [frame_id] <> "43-Ask2-ADJ0A-Exposition" and [frame_id] <> "43-Ask2-ADJ0A-Exposition-repeat-1" and [frame_id] <> "45-Ask1-ADJ0B-Exposition" and [frame_id] <> "45-Ask1-ARG0A-Exposition" and [frame_id] <> "45-Ask2-ADJ1A-Exposition" and [frame_id] <> "47-rest" and [frame_id] <> "49-Ask1-ARG0B-Exposition" and [frame_id] <> "49-Ask2-ARG1B-Exposition" and [frame_id] <> "49-Promise1-ADJ2A-Exposition" and [frame_id] <> "5-character-intro2" and [frame_id] <> "51-Ask1-ADJ2B-Exposition" and [frame_id] <> "51-Ask2-ADJ0A-Exposition" and [frame_id] <> "51-Promise1-ARG0B-Exposition" and [frame_id] <> "53-Ask1-ARG1A-Exposition" and [frame_id] <> "53-Ask2-ARG0A-Exposition" and [frame_id] <> "53-Promise1-ARG2B-Exposition" and [frame_id] <> "55-Ask1-ADJ1B-Exposition" and [frame_id] <> "55-Ask2-ARG2B-Exposition" and [frame_id] <> "55-Promise1-ADJ0B-Exposition" and [frame_id] <> "57-Ask1-ARG2B-Exposition" and [frame_id] <> "57-Ask2-ADJ2A-Exposition" and [frame_id] <> "57-Promise1-ADJ1B-Exposition" and [frame_id] <> "59-Ask1-ADJ0B-Exposition" and [frame_id] <> "59-Ask2-ADJ1B-Exposition" and [frame_id] <> "59-Promise1-ARG1B-Exposition" and [frame_id] <> "7-Ask2-ARG2B-Exposition" and [frame_id] <> "7-Promise1-ARG1A-Exposition" and [frame_id] <> "7-Promise1-ARG1A-Exposition-repeat-1" and [frame_id] <> "7-Promise2-ADJ1A-Exposition" and [frame_id] <> "9-Ask2-ARG0B-Exposition" and [frame_id] <> "9-Ask2-ARG0B-Exposition-repeat-1" and [frame_id] <> "9-Promise1-ADJ0A-Exposition" and [frame_id] <> "9-Promise2-ARG0B-Exposition")),
    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","INSERT_IMG_REPOSITORY_URL/button_","",Replacer.ReplaceText,{"value"}),
    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value", each ([frame_id] <> "21-Ask1-ARG1A-Exposition" and [frame_id] <> "23-Ask1-ARG2B-Exposition" and [frame_id] <> "25-Ask1-ARG0B-Exposition" and [frame_id] <> "27-Ask1-ADJ1B-Exposition" and [frame_id] <> "29-Ask1-ADJ2B-Exposition" and [frame_id] <> "31-Ask1-ADJ0A-Exposition" and [frame_id] <> "37-Ask2-ADJ0B-Exposition" and [frame_id] <> "39-Ask2-ADJ1A-Exposition" and [frame_id] <> "43-Ask2-ARG0A-Exposition" and [frame_id] <> "45-Ask2-ARG1B-Exposition")),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered Rows1", "frame_id", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"frame_id.1", "frame_id.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"frame_id.1", Int64.Type}, {"frame_id.2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"frame_id.1"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns1",{{"frame_id.2", Order.Ascending}}),
    #"Filtered Rows2" = Table.SelectRows(#"Sorted Rows", each ([frame_id.2] <> "Ask1-ADJ0A-Exposition" and [frame_id.2] <> "Ask1-ADJ0A-Exposition-repeat-1" and [frame_id.2] <> "Ask1-ADJ0B-Exposition" and [frame_id.2] <> "Ask1-ADJ0B-Exposition-repeat-1" and [frame_id.2] <> "Ask1-ADJ1A-Exposition" and [frame_id.2] <> "Ask1-ADJ1B-Exposition" and [frame_id.2] <> "Ask1-ADJ2A-Exposition" and [frame_id.2] <> "Ask1-ADJ2A-Exposition-repeat-1" and [frame_id.2] <> "Ask1-ADJ2B-Exposition" and [frame_id.2] <> "Ask1-ARG0A-Exposition" and [frame_id.2] <> "Ask1-ARG0A-Exposition-repeat-1") and ([key] = "selectedImage")),
    #"Sorted Rows1" = Table.Sort(#"Filtered Rows2",{{"child_hashed_id", Order.Ascending}, {"frame_id.2", Order.Ascending}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Sorted Rows1",{"key", "response_uuid"})
in
    #"Removed Columns2"